version: "3.9"

services:

  postgres:
    image: postgres:18

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ecommerce

    ports:
      - "5432:5432"

  backend:
    build: .

    ports:
      - "8000:8000"

    depends_on:
      - postgres